name: 'Dart Package Publisher'
description: 'Publish Dart Package To Pub.dev'
author: 'k-paxian'
branding:
  color: 'blue'
  icon: 'feather'
inputs: 
  accessToken:
    description: 'Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN'
    required: true
  refreshToken:
    description: 'Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN'
    required: true
  package:
    description: 'Dart package name, from pubspec.yaml'
    required: true
  relativePath:
    description: 'Path to your package root in your repository'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.accessToken }}
    - ${{ inputs.refreshToken }}
    - ${{ inputs.package }}
    - ${{ inputs.relativePath }}    
