name: 'Dart Package Publisher'
description: 'Continuously Test & Publish Dart Package To Pub.dev'
author: 'k-paxian'
branding:
  color: 'blue'
  icon: 'package'
inputs: 
  accessToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN'
    required: true
  refreshToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN'
    required: true
  relativePath:
    description: '(Optional) Path to your package root in your repository'
    required: false
    default: ''
  flutter:
    description: '(Optional) Declares a package as a Flutter package'
    required: false
    default: false
  dryRunOnly:
    description: '(Optional) Perform dry run only, no real publishing'
    required: false
    default: false
  skipTests:
    description: '(Optional) Skip unit tests run'
    required: false
    default: false
  suppressBuildRunner:
    description: '(Optional) Suppress using `build_runner` for unit tests run'
    required: false
    default: false
outputs:
  success:
    description: 'Result, "true" if actual publishing happened, "false" otherwise'
  package:
    description: 'Package name from pubspec'
  localVersion:
    description: 'Package local version from pubspec'
  remoteVersion:
    description: 'Package remote version from pub.dev'
  dartVersion:
    description: 'Dart SDK version which is being used to run tests & publish'
  flutterVersion:
    description: 'Flutter SDK version which is being used to run tests & publish'
runs:
  using: 'docker'
  image: 'Dockerfile'
