name: 'Dart Package Publisher'
description: 'Publish Dart Package To Pub.dev'
author: 'k-paxian'
branding:
  color: 'blue'
  icon: 'feather'
inputs: 
  accessToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN'
    required: true
  refreshToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN'
    required: true
  relativePath:
    description: '(Optional) Path to your package root in your repository'
    required: false
    default: '.'
  dryRunOnly:
    description: '(Optional) Perform dry run only, no real publishing'
    required: false
    default: false
outputs:
  package:
    description: 'Package name from pubspec'
  localVersion:
    description: 'Package local version from pubspec'
  remoteVersion:
    description: 'Package remote version from pub.dev'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.accessToken }}
    - ${{ inputs.refreshToken }}
    - ${{ inputs.relativePath }}
    - ${{ inputs.dryRunOnly }}
