name: 'Dart Package Publisher'
description: 'Continuously Test & Publish Dart Package To Pub.dev'
author: 'k-paxian'
branding:
  color: 'blue'
  icon: 'package'
inputs: 
  accessToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN'
    required: true
  refreshToken:
    description: '(Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN'
    required: true
  relativePath:
    description: '(Optional) Path to your package root in your repository'
    required: false
    default: '.'
  flutterVersion:
    description: '(Optional) Declares a package as a Flutter package. Should contain valid Flutter version, like `v1.12.13+hotfix.5`'
    required: false
    default: ''
  dryRunOnly:
    description: '(Optional) Perform dry run only, no real publishing'
    required: false
    default: false
  skipTests:
    description: '(Optional) Skip unit tests run'
    required: false
    default: false
  suppressBuildRunner:
    description: '(Optional) Suppress using build_runner for unit tests run'
    required: false
    default: false
outputs:
  package:
    description: 'Package name from pubspec'
  localVersion:
    description: 'Package local version from pubspec'
  remoteVersion:
    description: 'Package remote version from pub.dev'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - FLUTTER_VERSION: ${{ inputs.flutterVersion }}
